name: BUILD
on:
  workflow_dispatch:
jobs:
  build:
    name: Build driver samples
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'recursive'
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64

    - uses: lukka/get-cmake@latest
    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11
    - name: setup devcmd
      uses: ilammy/msvc-dev-cmd@latest
      
    - name: Retrieve and build all available solutions
      run: |
          dir tools\servicing
          cd .\tools\servicing\
          .\build.cmd
          cd ..\..\
          dir tools\borderline
          cd .\tools\bordeline\
          .\tools\borderline\build.cmd
          dir /s /b 
